# Generated by Django 3.0.2 on 2020-01-31 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keystoneapp', '0003_auto_20200131_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationdata',
            old_name='jambnumber',
            new_name='regnumber',
        ),
    ]
